env_files:
  github_token: ~/.config/goreleaser/github_token
before:
  hooks:
    - make clean
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - amd64
  ldflags:
    - -s -w -X main.version={{ replace .Version "v" "" }}
archives:
- name_template: '{{ .ProjectName }}-{{ replace .Version "v" "" }}-{{ .Os }}-{{ .Arch }}'
  files:
    - LICENSE
    - README.md
    - CHANGELOG.md
    - docs/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
brews:
- name: bonclay
  github:
    owner: talal
    name: homebrew-tap
  folder: Formula
  homepage: "https://github.com/talal/bonclay"
  description: "A fast and minimal backup tool"
  install: bin.install "bonclay"
